//
//  CharityDetailModels.swift
//  Compassion
//
//  Created by Casper Daris on 30/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharityDetail {
    
    enum Charity {
        
        struct Request {
            let name: String
            let logoUrl: String
        }
        
        struct Response {
            let logo: UIImage
        }
        
        struct ViewModel {
            let logo: UIImage
        }
    }
    
    enum Favorite {
        
        struct Request {
            let charity: CharityModel
            let initialState: Bool
        }
        
        struct Response {
            let message: String
            let isNowFavorite: Bool
        }
        
        struct ViewModel {
            let message: String
            let isNowFavorite: Bool
        }
    }
    
    enum Reaction {
        struct Request {
        }
        struct Response {
            let reactions: [ReactionModel]
        }
        struct ViewModel {
            let reactions: [ReactionModel]
        }
    }
}
