//
//  SearchFilterPopUpPresenter.swift
//  Compassion
//
//  Created by Casper Daris on 17/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol SearchFilterPopUpPresenterProtocol {
    func set(viewController: SearchFilterPopUpViewControllerProtocol?)

    func presentFilterView(cities: [String], sectors: [String])
}

class SearchFilterPopUpPresenter: SearchFilterPopUpPresenterProtocol {

    // MARK: - DI
    weak var viewController: SearchFilterPopUpViewControllerProtocol?

    func set(viewController: SearchFilterPopUpViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: - Methods
extension  SearchFilterPopUpPresenter {

    func presentFilterView(cities: [String], sectors: [String]) {
        viewController?.displayFilters(cities: cities, sectors: sectors)
    }
}
