//
//  LoginPresenter.swift
//  Compassion
//
//  Created by Casper Daris on 02/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol LoginPresenterProtocol {
    func set(viewController: LoginViewControllerProtocol?)

    func presentLogin()
    func presentNotAbleToLogin(error: String)
    func presentSuccesfullLogin()
}

class LoginPresenter: LoginPresenterProtocol {

    // MARK: - DI
    weak var viewController: LoginViewControllerProtocol?

    func set(viewController: LoginViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  LoginPresenter {

    func presentLogin() {
        viewController?.displayLogin()
    }
    
    func presentNotAbleToLogin(error: String) {
        viewController?.displayLoginError(error: error)
    }
    
    func presentSuccesfullLogin() {
        viewController?.succesfullUserLogin()
    }
}
