//
//  LoginModels.swift
//  Compassion
//
//  Created by Casper Daris on 21/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
  // MARK: Use cases
  
  enum Login {
    struct Request {
        let email: String
        let password: String
    }
    
    struct Response {
    }
    
    struct ViewModel {
    }
  }
}
