//
//  PrivacyPresenter.swift
//  Compassion
//
//  Created by Casper Daris on 17/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol PrivacyPresenterProtocol {
    func set(viewController: PrivacyViewControllerProtocol?)

    func presentPrivacy()
}

class PrivacyPresenter: PrivacyPresenterProtocol {

    // MARK: - DI
    weak var viewController: PrivacyViewControllerProtocol?

    func set(viewController: PrivacyViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: - Methods
extension  PrivacyPresenter {

    func presentPrivacy() {
        viewController?.displayPrivacy()
    }
}
