//
//  SettingsInteractor.swift
//  Compassion
//
//  Created by Casper Daris on 10/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol SettingsInteractorProtocol {
    func handleSettingsDidLoad()
}

class SettingsInteractor: SettingsInteractorProtocol {
    
    // MARK: - DI
    var presenter: SettingsPresenterProtocol
    
    init(presenter: SettingsPresenterProtocol) {
        self.presenter = presenter
    }
    
    func handleSettingsDidLoad() {
        presenter.presentSettings()
    }
}
