//
//  SearchPresenter.swift
//  Compassion
//
//  Created by Casper Daris on 02/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol SearchPresenterProtocol {
    typealias Response = Search.LoadScene.Response
    
    func set(viewController: SearchViewControllerProtocol?)

    func presentSearch(response: Response)
}

class SearchPresenter: SearchPresenterProtocol {

    // MARK: - DI
    weak var viewController: SearchViewControllerProtocol?

    func set(viewController: SearchViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: - Methods
extension  SearchPresenter {

    func presentSearch(response: Response) {
        viewController?.displaySearch(viewModel: .init(userProfile: response.userProfile,
                                                       charities: response.charities))
    }
}
