//
//  SearchModels.swift
//  Compassion
//
//  Created by Casper Daris on 20/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search {
    
    enum LoadScene {
        struct Request {
            let city: String
            let sector: String
            let limit: Int
        }
        
        struct Response {
            let userProfile: UserProfile
            let charities: [CharityModel]
        }
        
        struct ViewModel {
            let userProfile: UserProfile
            let charities: [CharityModel]
        }
    }
}
