//
//  LocationPresenter.swift
//  Compassion
//
//  Created by Casper Daris on 13/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol LocationPresenterProtocol {
    func set(viewController: LocationViewControllerProtocol?)

    func presentLocationSettings()
}

class LocationPresenter: LocationPresenterProtocol {

    // MARK: - DI
    weak var viewController: LocationViewControllerProtocol?

    func set(viewController: LocationViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: - Methods
extension LocationPresenter {

    func presentLocationSettings() {
        viewController?.displayLocationSettings()
    }
}
