//
//  LoginViewControllerTests.swift
//  Compassion
//
//  Created by Casper Daris on 14/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Compassion
import XCTest
import SwiftyMocky

class LoginViewControllerTests: XCTestCase {

    // MARK: - Mocks
    private let mockRouter = LoginRouterProtocolMock()
    private let mockInteractor = LoginInteractorProtocolMock()

    // MARK: - Setup
    override func setUp() {
        Matcher.default.register(LoginRequestMock.self) { lhs, rhs -> Bool in
            return lhs.email == rhs.email && lhs.password == rhs.password
        }
    }
    
    // MARK: - Tests
    func testViewDidLoad() {
        let sut = createViewController()
        sut.viewDidLoad()
    }
    
    func testDisplayLogin() {
        let sut = createViewController()
        sut.displayLogin()
    }
    
    func testDisplayLoginError() {
        let sut = createViewController()
        sut.viewDidLoad()
        sut.displayLoginError(error: "Test Error")
    }
    
    func testSuccesfullUserLogin() {
        let sut = createViewController()
        sut.viewDidLoad()
        sut.succesfullUserLogin()
    }
    
}

// MARK: - Privates
private extension  LoginViewControllerTests {

    func createViewController() ->  LoginViewController {
        let storyboard = UIStoryboard(name: "Login", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "Login") as! LoginViewController
        vc.set(router: mockRouter)
        vc.set(interactor: mockInteractor)
        vc.loadViewIfNeeded()
        vc.viewDidLoad()
        vc.viewWillAppear(false)
        vc.viewDidAppear(false)
        return vc
    }
}
