//
//  LoginPresenterTests.swift
//  Compassion
//
//  Created by Casper Daris on 14/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Compassion
import XCTest
import SwiftyMocky

class LoginPresenterTests: XCTestCase {

    // MARK: - Mocks
    private let mockViewController = LoginViewControllerProtocolMock()

    // MARK: - Test lifecycle
    override func setUp() {
        
    }

    // MARK: - Tests
    func testPresentLogin() {
        let sut = createPresenter()
        sut.presentLogin()
//        Verify(mockViewController, .displayLogin())
    }
    
    func testPresentNotABleToLogin() {
        let sut = createPresenter()
        let error = "Test Error"
        sut.presentNotAbleToLogin(error: error)
//        Verify(mockViewController, .displayLoginError(error: .value(error)))
    }
    
    func testPresentSuccesfullLogin() {
        let sut = createPresenter()
        sut.presentSuccesfullLogin()
//        Verify(mockViewController, .succesfullUserLogin())
    }
}

// MARK: - Privates
private extension LoginPresenterTests {

    func createPresenter() -> LoginPresenter {
        let presenter =  LoginPresenter()
        presenter.set(viewController: mockViewController)
        return presenter
    }
}


