////
//  NewReactionRouter.swift
//  Compassion
//
//  Created by Casper Daris on 09/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol NewReactionRouterProtocol {
  func set(viewController: NewReactionViewControllerProtocol?)
  func route(to scene: NewReactionRouter.Scene)
}

class NewReactionRouter: NSObject, NewReactionRouterProtocol {

    //MARK: - DI
    weak var viewController: NewReactionViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol

    func set(viewController: NewReactionViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(rootNavigator: RootNavigatorProtocol) {
        self.rootNavigator = rootNavigator
    }
}

// MARK: - Routing logic
extension NewReactionRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: NewReactionRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

