//
//  NewReactionModels.swift
//  Compassion
//
//  Created by Casper Daris on 10/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewReaction {
    // MARK: Use cases
    
    enum NewReaction {
        struct Request {
            let reaction: String
            let charity: String
        }
        
        struct Response {
            let message: String
            let success: Bool
        }
        
        struct ViewModel {
            let message: String
            let success: Bool
        }
    }
}
