//
//  NewReactionPresenter.swift
//  Compassion
//
//  Created by Casper Daris on 09/05/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol NewReactionPresenterProtocol {
    typealias Response = NewReaction.NewReaction.Response
    
    func set(viewController: NewReactionViewControllerProtocol?)

    func presentNewReactionView(user: String)
    func presentPlaceNewReaction(response: Response)
}

class NewReactionPresenter: NewReactionPresenterProtocol {

    // MARK: - DI
    weak var viewController: NewReactionViewControllerProtocol?

    func set(viewController: NewReactionViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: - Methods
extension  NewReactionPresenter {

    func presentNewReactionView(user: String) {
        viewController?.displayNewReaction(user: user)
    }
    
    func presentPlaceNewReaction(response: Response) {
        viewController?.newReactionPlaced(viewModel: .init(message: response.message, success: response.success))
    }
}
