//
//  AboutAppInteractor.swift
//  Compassion
//
//  Created by Casper Daris on 17/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol AboutAppInteractorProtocol {
    func handleDidLoadAbout()
}

class AboutAppInteractor: AboutAppInteractorProtocol {

    // MARK: - DI
    var presenter: AboutAppPresenterProtocol

    init(presenter: AboutAppPresenterProtocol) {
        self.presenter = presenter
    }
    
    func handleDidLoadAbout() {
        presenter.presentAboutApp()
    }
}
