//
//  RegisterPresenter.swift
//  Compassion
//
//  Created by Casper Daris on 02/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol RegisterPresenterProtocol {
    typealias Response = Register.User.Response
    
    func set(viewController: RegisterViewControllerProtocol?)

    func presentRegister()
    func presentRegisterError(error: String)
    
    func presentNewUser()
}

class RegisterPresenter: RegisterPresenterProtocol {

    // MARK: - DI
    weak var viewController: RegisterViewControllerProtocol?

    func set(viewController: RegisterViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: - Methods
extension  RegisterPresenter {

    func presentRegister() {
        viewController?.displayRegister()
    }
    
    func presentRegisterError(error: String) {
        viewController?.displayRegisterError(error: error)
    }
    
    func presentNewUser() {
        viewController?.registerNewUser()
    }
}
