//
//  CharityDetailViewControllerTests.swift
//  Compassion
//
//  Created by Casper Daris on 06/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Compassion
import XCTest
import SwiftyMocky

class CharityDetailViewControllerTests: XCTestCase {
    
    // MARK: - Mocks
    private let mockRouter = CharityDetailRouterProtocolMock()
    private let mockInteractor = CharityDetailInteractorProtocolMock()
    private let mockTableViewDataSource = ReactionTableViewDataSourceProtocolMock()
    
    // MARK: - Test lifecycle
    override func setUp() {
        Matcher.default.register(CharityModelMock.self) { lhs, rhs -> Bool in
            return lhs.email == rhs.email &&
                lhs.adres == rhs.adres &&
                lhs.description == rhs.description &&
                lhs.logoUrl == rhs.logoUrl &&
                lhs.name == rhs.name &&
                lhs.phone == rhs.phone &&
                lhs.sector == rhs.sector &&
                lhs.website == rhs.website
            
        }
    }
    
    // MARK: - Tests
    func testViewDidLoad() {
        let sut = createViewController()
        sut.viewDidLoad()
    }
    
    func testFavoriteTapped() {
        let sut = createViewController()
        sut.displayedCharity = CharityModelMock.mock()
        sut.favoriteTapped()
        Verify(mockInteractor, .handleFavoriteButtonTapped(request: .any))
    }
}

// MARK: Privates
private extension  CharityDetailViewControllerTests {
    
    func createViewController() -> CharityDetailViewController {
        let storyboard = UIStoryboard(name: "Search", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "Detail") as! CharityDetailViewController
        vc.set(router: mockRouter)
        vc.set(interactor: mockInteractor)
        vc.loadViewIfNeeded()
        vc.viewDidLoad()
        vc.viewWillAppear(false)
        vc.viewDidAppear(false)
        return vc
    }
}
