//
//  MainInteractor.swift
//  Compassion
//
//  Created by Casper Daris on 09/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import Combine
import Firebase

protocol MainInteractorProtocol {
    typealias Request = MainModels.LoadTabBarItems.Request
    
    func handleMainDidLoad(request: Request)
}

class MainInteractor: MainInteractorProtocol {
    
    // MARK: - DI
    var presenter: MainPresenterProtocol
    private let profileManager: ProfileManagerProtocol
    
    init(presenter: MainPresenterProtocol,
         profileManager: ProfileManagerProtocol) {
        self.presenter = presenter
        self.profileManager = profileManager
    }
    
    func handleMainDidLoad(request: Request) {
        self.presenter.presentMain(response: .init(tabBarItems: TabBarItem.allCases))
    }
}
