////
//  MainRouter.swift
//  Compassion
//
//  Created by Casper Daris on 09/04/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol MainRouterProtocol {
    func set(viewController: MainViewControllerProtocol?)
    func route(to scene: MainRouter.Scene)
}

class MainRouter: NSObject, MainRouterProtocol {
    
    //MARK: DI
    weak var viewController: MainViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    
    func set(viewController: MainViewControllerProtocol?) {
        self.viewController = viewController
    }
    
    init(rootNavigator: RootNavigatorProtocol) {
        self.rootNavigator = rootNavigator
    }
}

// MARK: Routing logic
extension MainRouter {
    
    enum Scene {
        case destination1
    }
    
    func route(to scene: MainRouter.Scene) {
        switch scene {
            case .destination1:
                /// TODO: Implement routing
                break
        }
    }
}

